version: '3.7'

services:
  user_db:
    container_name: user_db
    hostname: user
    image: postgres:15.0-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
      - POSTGRES_HOST=user
    volumes: 
      - user_data:/var/lib/postgresql/data

  user_service:
    container_name: user_service
    image: user_service
    ports:
      - "4001:4001"
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@user:5432/user_db
    build:
        context: ..
        args:
            BIN: user
    depends_on:
      - user_db
